[project]
name = "aprendizaje-automatico-2c2026"
version = "0.1.0"
description = "Repo para la materia 'Aprendizaje Automático'"
readme = "README.md"
authors = [
    { name = "Gerardo1909", email = "gerardotoboso1909@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.9",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "statsmodels>=0.15.0",
]

[tool.uv]
package = false
